name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Install memcache/redis tool
      run: |
        sudo apt-get update
        sudo apt-get install memcached redis-server
        memcached -d  
  
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
